# Depression Prediction Analysis

## Introduction

In this Notebook we will be exploring the relationship between various factors and depression level in nearly 40,000 survey respondents.

The data that we will be using comes from an online survey which asked the 42 question version of the Depression Anxiety Stress Scales (DASS), which can be found [here](http://www2.psy.unsw.edu.au/dass/).

The data owner Paleg (2021) describes the data as follows (some formatting mine):

    "The survey was open to anyone and people were motivated to take it to get personalized results. At the end of the test they also were given the option to complete a short research survey. This datatset comes from those who agreed to complete the research survey and answered yes to the question "Have you given accurate answers and may they be used for research?" at the end. 
    
    This data was collected 2017 - 2019." 
    
    The following items were included in the survey:
    
    * Q1	 I found myself getting upset by quite trivial things.
    * Q2	 I was aware of dryness of my mouth.
    * Q3	 I couldn't seem to experience any positive feeling at all.
    * Q4	 I experienced breathing difficulty (eg, excessively rapid breathing, breathlessness in the absence of physical exertion).
    * Q5     I just couldnt seem to get going.
    * Q6     I tended to over-react to situations.
    * Q7     I had a feeling of shakiness (eg, legs going to give way).
    * Q8     I found it difficult to relax.
    * Q9     I found myself in situations that made me so anxious I was most relieved when they ended.
    * Q10	I felt that I had nothing to look forward to.
    * Q11	I found myself getting upset rather easily.
    * Q12	I felt that I was using a lot of nervous energy.
    * Q13	I felt sad and depressed.
    * Q14	I found myself getting impatient when I was delayed in any way (eg, elevators, traffic lights, being kept waiting).
    * Q15	I had a feeling of faintness.
    * Q16	I felt that I had lost interest in just about everything.
    * Q17	I felt I wasn&#39;t worth much as a person.
    * Q18	I felt that I was rather touchy.
    * Q19	I perspired noticeably (eg, hands sweaty) in the absence of high temperatures or physical exertion.
    * Q20	I felt scared without any good reason.
    * Q21	I felt that life wasn&#39;t worthwhile.
    * Q22	I found it hard to wind down.
    * Q23	I had difficulty in swallowing.
    * Q24	I couldn&#39;t seem to get any enjoyment out of the things I did.
    * Q25	I was aware of the action of my heart in the absence of physical exertion (eg, sense of heart rate increase, heart missing a beat).
    * Q26	I felt down-hearted and blue.
    * Q27	I found that I was very irritable.
    * Q28	I felt I was close to panic.
    * Q29	I found it hard to calm down after something upset me.
    * Q30	I feared that I would be &quot;thrown&quot; by some trivial but unfamiliar task.
    * Q31	I was unable to become enthusiastic about anything.
    * Q32	I found it difficult to tolerate interruptions to what I was doing.
    * Q33	I was in a state of nervous tension.
    * Q34	I felt I was pretty worthless.
    * Q35	I was intolerant of anything that kept me from getting on with what I was doing.
    * Q36	I felt terrified.
    * Q37	I could see nothing in the future to be hopeful about.
    * Q38	I felt that life was meaningless.
    * Q39	I found myself getting agitated.
    * Q40	I was worried about situations in which I might panic and make a fool of myself.
    * Q41	I experienced trembling (eg, in the hands).
    * Q42	I found it difficult to work up the initiative to do things.
    
    This response is stored in variable A (e.g. Q1A). Also recorded was the time taken in milliseconds to answer that question (E) and that question's position in the survey (I).

    These other durations were also recorded (measured on the server's side):

    introelapse: The time spent on the introduction/landing page (in seconds)
    testelapse: The time spent on all the DASS questions (should be equivalent to the time elapsed on all the indiviudal questions combined)
    surveyelapse: The time spent answering the rest of the demographic and survey questions

    On the next page was a generic demographics survey with many different questions.

    The Ten Item Personality Inventory was administered (see Gosling, S. D., Rentfrow, P. J., & Swann, W. B., Jr. (2003). A Very Brief Measure of the Big Five Personality Domains. Journal of Research in Personality, 37, 504-528.):

    * TIPI1: Extraverted, enthusiastic.
    * TIPI2: Critical, quarrelsome.
    * TIPI3: Dependable, self-disciplined.
    * TIPI4: Anxious, easily upset.
    * TIPI5: Open to new experiences, complex.
    * TIPI6: Reserved, quiet.
    * TIPI7: Sympathetic, warm.
    * TIPI8: Disorganized, careless.
    * TIPI9: Calm, emotionally stable.
    * TIPI10: Conventional, uncreative.

    The TIPI items were rated "I see myself as:" _____ such that

    1 = Disagree strongly
    2 = Disagree moderately
    3 = Disagree a little
    4 = Neither agree nor disagree
    5 = Agree a little
    6 = Agree moderately
    7 = Agree strongly



    The following items were presented as a check-list and subjects were instructed "In the grid below, check all the words whose definitions you are sure you know":

    * VCL1: boat
    * VCL2: incoherent
    * VCL3: pallid
    * VCL4: robot
    * VCL5: audible
    * VCL6: cuivocal
    * VCL7: paucity
    * VCL8: epistemology
    * VCL9: florted
    * VCL10: decide
    * VCL11: pastiche
    * VCL12: verdid
    * VCL13: abysmal
    * VCL14: lucid
    * VCL15: betray
    * VCL16: funny

    A value of 1 is checked, 0 means unchecked. The words at VCL6, VCL9, and VCL12 are not real words and can be used as a validity check.

    A bunch more questions were then asked:


    * education: "How much education have you completed?"
        * 1=Less than high school
        * 2=High school
        * 3=University degree
        * 4=Graduate degree
    * urban: "What type of area did you live when you were a child?"
        * 1=Rural (country side)
        * 2=Suburban
        * 3=Urban (town, city)
    * gendee: "What is your gender?"
        * 1=Male
        * 2=Female
        * 3=Other
    * engnat: "Is English your native language?"
        * 1=Yes
        * 2=No
    * age: "How many years old are you?"
    * hand: "What hand do you use to write with?"
        * 1=Right
        * 2=Left
        * 3=Both
    * religion: "What is your religion?"
        * 1=Agnostic
        * 2=Atheist
        * 3=Buddhist
        * 4=Christian (Catholic)
        * 5=Christian (Mormon)
        * 6=Christian (Protestant)
        * 7=Christian (Other)
        * 8=Hindu
        * 9=Jewish
        * 10=Muslim
        * 11=Sikh
        * 12=Other
    * orientation: "What is your sexual orientation?"
        * 1=Heterosexual
        * 2=Bisexual
        * 3=Homosexual
        * 4=Asexual
        * 5=Other
    * race: "What is your race?"
        * 10=Asian
        * 20=Arab
        * 30=Black
        * 40=Indigenous Australian
        * 50=Native American
        * 60=White
        * 70=Other
    * voted: "Have you voted in a national election in the past year?"
        * 1=Yes
        * 2=No
    * married: "What is your marital status?"
        * 1=Never married
        * 2=Currently married
        * 3=Previously married
    * familysize: "Including you, how many children did your mother have?"		
    * major: "If you attended a university, what was your major (e.g. "psychology", "English", "civil engineering")?"

    The following values were derived from technical information:

    country: ISO country code of where the user connected from
    screensize: 
        1=device with small screen (phone, etc)
        2=device with big screen (laptop, desktop, etc)
    uniquenetworklocation:
        1=only one survey from user's specific network in dataset
        2=multiple surveys submitted from the network of this user  (2 does not necessarily imply duplicate records for an individual, as it could be different students at a single school or different memebers of the same household; and even if 1 there still could be duplicate records from a single individual e.g. if they took it once on their wifi and once on their phone)
    source - how the user found the test:
        1=from the front page of the site hosting the survey
        2=from google, 0=other or unknown

p([1](#1))

We will be assessing these variable to find their relationship to depression scores in survey respondents in order to build a model that can be used to predict depression based on these factors.

## Cleaning
----

#### Initial Imports

In [134]:
# import libraries
import pandas as pd
import numpy as np
from functions import *
from spellchecker import SpellChecker

# ignore warnings
import warnings
warnings.filterwarnings('ignore')

#### Read In Data

In [135]:
# read in data (tab seperated)
data = pd.read_csv('data.csv', sep='\t')

# make it so we can view all columns
pd.set_option('max_columns', None)

#### View Data

In [136]:
# view data
data.head()

,Q1A,Q1I,Q1E,Q2A,Q2I,Q2E,Q3A,Q3I,Q3E,Q4A,Q4I,Q4E,Q5A,Q5I,Q5E,Q6A,Q6I,Q6E,Q7A,Q7I,Q7E,Q8A,Q8I,Q8E,Q9A,Q9I,Q9E,Q10A,Q10I,Q10E,Q11A,Q11I,Q11E,Q12A,Q12I,Q12E,Q13A,Q13I,Q13E,Q14A,Q14I,Q14E,Q15A,Q15I,Q15E,Q16A,Q16I,Q16E,Q17A,Q17I,Q17E,Q18A,Q18I,Q18E,Q19A,Q19I,Q19E,Q20A,Q20I,Q20E,Q21A,Q21I,Q21E,Q22A,Q22I,Q22E,Q23A,Q23I,Q23E,Q24A,Q24I,Q24E,Q25A,Q25I,Q25E,Q26A,Q26I,Q26E,Q27A,Q27I,Q27E,Q28A,Q28I,Q28E,Q29A,Q29I,Q29E,Q30A,Q30I,Q30E,Q31A,Q31I,Q31E,Q32A,Q32I,Q32E,Q33A,Q33I,Q33E,Q34A,Q34I,Q34E,Q35A,Q35I,Q35E,Q36A,Q36I,Q36E,Q37A,Q37I,Q37E,Q38A,Q38I,Q38E,Q39A,Q39I,Q39E,Q40A,Q40I,Q40E,Q41A,Q41I,Q41E,Q42A,Q42I,Q42E,country,source,introelapse,testelapse,surveyelapse,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,uniquenetworklocation,hand,religion,orientation,race,voted,married,familysize,major
0,4,28,3890,4,25,2122,2,16,1944,4,8,2044,4,34,2153,4,33,2416,4,10,2818,4,13,2259,2,21,5541,1,38,4441,4,31,2451,4,24,3325,4,14,1416,4,37,5021,4,27,2342,4,39,2480,3,6,2476,4,35,1627,3,17,9050,3,30,7001,1,11,4719,4,20,2984,4,36,1313,4,42,2444,4,1,9880,4,2,4695,4,5,1677,3,4,6723,4,3,5953,2,26,8062,4,12,5560,4,7,3032,2,29,3316,3,40,3563,4,23,5594,4,41,1477,1,18,3885,2,9,5265,4,19,1892,3,22,4228,4,32,1574,4,15,2969,IN,2,19,167,166,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,1,12,1,10,2,1,2,NaN
1,4,2,8118,1,36,2890,2,35,4777,3,28,3090,4,10,5078,4,40,2790,3,18,3408,4,1,8342,3,37,916,2,32,1537,2,21,3926,2,25,3691,4,26,2004,4,4,8888,3,27,4109,3,19,4058,4,12,3692,2,6,3373,1,23,6015,1,16,3023,2,22,2670,3,3,5727,1,39,3641,2,33,2670,2,7,7649,3,11,2537,3,5,2907,4,9,1685,3,41,4726,3,17,6063,2,20,3307,3,14,4995,3,38,2505,2,34,2540,2,31,4359,3,15,3925,4,13,4609,2,30,3755,2,42,2323,1,24,5713,2,8,1334,2,29,5562,US,2,1,193,186,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,1,2,7,0,70,2,1,4,NaN
2,3,7,5784,1,33,4373,4,41,3242,1,13,6470,4,11,3927,3,9,3704,1,17,4550,3,5,3021,2,32,5864,4,21,3722,2,10,3424,1,36,3236,4,23,2489,1,34,7290,4,12,6587,4,22,3627,4,38,2905,2,18,2998,2,8,10233,1,16,4258,4,28,2888,3,4,59592,2,3,11732,4,2,8834,2,29,7358,1,30,4928,2,15,3036,1,19,4127,2,37,3934,2,26,10782,4,1,8273,3,39,3501,1,27,3824,4,25,2141,3,6,17461,4,24,1557,4,40,4446,4,42,1883,2,35,5790,2,14,4432,1,20,2203,4,31,5768,PL,2,5,271,122,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,1,4,3,60,1,1,3,NaN
3,2,23,5081,3,11,6837,2,37,5521,1,27,4556,3,28,3269,3,26,3231,4,2,7138,2,19,3079,3,31,9650,3,17,4179,2,5,5928,1,21,2838,1,20,2560,4,29,5139,2,22,3597,2,35,3336,3,10,4506,1,14,2695,1,25,8128,2,15,3125,1,6,4061,1,40,4272,1,12,4029,1,9,5630,1,18,30631,2,24,9870,4,4,2411,1,16,9478,3,1,7618,3,32,12639,3,34,5378,1,41,8923,2,38,2977,4,3,5620,1,7,16760,1,8,6427,2,39,3760,1,13,4112,3,42,2769,4,33,4432,4,30,3643,2,36,3698,US,2,3,261,336,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,1,2,4,5,70,2,1,5,biology
4,2,36,3215,2,13,7731,3,5,4156,4,10,2802,4,2,5628,2,9,6522,4,34,2374,4,11,3054,4,7,2975,3,14,3524,2,33,3033,4,23,2132,4,17,1314,4,16,3181,4,26,2249,3,19,2623,4,35,3093,4,38,7098,4,37,1938,4,15,3502,3,32,4776,3,18,4463,4,4,2436,2,40,4047,4,31,3787,4,42,2102,2,1,12351,4,3,2410,2,22,5056,4,39,3343,3,27,3012,4,20,3520,4,8,1868,4,25,2536,3,24,3725,4,30,2130,3,29,3952,3,21,10694,3,41,3231,4,12,3604,4,28,1950,3,6,6265,MY,2,1766,164,157,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,2,3,10,1,10,2,1,4,Psychology

Above we can see the data contained in our CSV file.

* 42 question responses with the values 1-4 labeled with the format Q#A.
* 42 indicators of the order the respondent received the question in labeled with the format Q#I.
* 42 indicators of the length of time the respondent spent on each question labeled with the format Q#E
* 10 responses with possible values of 1-7 indicating how much a respondent believed a certain statement applied to their personality labeled with the format TIPI#
* 16 responses to whether a respondent knew for a fact the definition of a certain word where 0 is 'No' and 1 is 'Yes' labeled with the format VLC#
    - VLC6, VLC9 ad VLC12 are made up words and are there to check the validity of the response.
* 3 indicators of the length of time the respondent took on parts of the survey and the survey as a whole
* The source indicating how the respondent came upon the survey.
* Demographic information and specifications about the respondents technology either gathered from the respondent by way of survey or through the use of technology.

#### Contents

In [137]:
# get data shape
get_size(data)

         Count
Columns    172
Rows     39775

We have 172 columns of information with 39,775 rows of respondents who we will hereout assume are unique individuals, though it is possible for some respondents to have taken the survery more than once.

#### Duplicate Values

In [138]:
# check for duplicated data
get_dupes(data)

There are no Duplicate Values

### Getting DASS Scores and Time Taken per Response Category

First we will get our DASS scores using the scoring guide found [here](https://neurocogsystem.com/wp-content/uploads/2021/02/DASS-42-Scoring.pdf).

According to this scoring guide which is based off of the DASS Manual questions number 3, 5, 10, 13, 16, 17, 21, 24, 26, 31, 34, 38 and 42 are the depression based questions. The anxiety based questions in this test are are 2, 4, 7, 9, 15, 19, 20, 23, 25, 28, 30, 36, 40, and 41. Finally the stress based questions are 1, 6, 8, 11, 12, 14, 18, 22, 27, 29, 32, 33, 35 and 39.

Each of the questions will be summed per category to come up with the total score per category per respondent.

We will also create columns to observe the amount of time the respondents took per category in milliseconds compared to the overall time in milliseconds to get a percentage of time taken overall per category. It may be interesting to see if the time taken per category has a relationship with depression.

Once we have derived this information, we will drop all of the Q#A, Q#I, and Q#E columns, as well as the time related columns, since they will not contain anymore information of interest to this analysis.

In [139]:
# list of column names of questions related to depression
depression_answers = ['Q3A', 'Q5A', 'Q10A', 'Q13A', 'Q16A', 'Q17A', 'Q21A', 'Q24A', 'Q26A', 'Q31A', 'Q34A', 'Q37A', 'Q38A', 'Q42A']

# list of column names of questions related to anxiety
anxiety_answers = ['Q2A', 'Q4A', 'Q7A', 'Q9A', 'Q15A', 'Q19A', 'Q20A', 'Q23A', 'Q25A', 'Q28A','Q30A', 'Q36A', 'Q40A', 'Q41A']

# list of column names of questions related to stress
stress_answers = ['Q1A', 'Q6A', 'Q8A', 'Q11A', 'Q12A', 'Q14A', 'Q18A', 'Q22A', 'Q27A', 'Q29A', 'Q32A', 'Q33A', 'Q35A', 'Q39A']

# create lists of time values for depression, anxiety and stress by taking the already initiated answer lists and getting their Q#E value instead
depression_time = [i.strip('A') + 'E' for i in depression_answers]
anxiety_time = [i.strip('A') + 'E' for i in anxiety_answers]
stress_time = [i.strip('A') + 'E' for i in stress_answers]

In [140]:
# creating new columns of depression, anxiety and stress sums per respondent
data['dep_score'] = data[depression_answers].sum(axis=1)
data['anx_score'] = data[anxiety_answers].sum(axis=1)
data['str_score'] = data[stress_answers].sum(axis=1)

# creating new columns of depression, anxiety and stress time sums per respondent
data['dep_time'] = data[depression_time].sum(axis=1)
data['anx_time'] = data[anxiety_time].sum(axis=1)
data['str_time'] = data[stress_time].sum(axis=1)

# a column of the total time in milliseconds to compare the time taken in each category to
data['total_time(ms)'] = data['dep_time'] + data['anx_time'] + data['str_time']

# making the time columns into percentages of the total time taken in milliseconds
data['dep_time'] = round(100 * data['dep_time']/data['total_time(ms)'], 2)
data['anx_time'] = round(100 * data['anx_time']/data['total_time(ms)'], 2)
data['str_time'] = round(100 * data['str_time']/data['total_time(ms)'], 2)

# create a list of all question columns
all_questions = depression_answers + anxiety_answers + stress_answers

# get the list of all 'question position' variables which follow the Q#I format
question_position = [i.strip('A') + 'I' for i in all_questions]

# drop all question variables which are now uneccessary
data = data.drop(columns=all_questions + depression_time + anxiety_time + stress_time + question_position
                         + ['total_time(ms)', 'introelapse', 'testelapse', 'surveyelapse'], errors = 'ignore')

In [141]:
data.head()

,country,source,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,uniquenetworklocation,hand,religion,orientation,race,voted,married,familysize,major,dep_score,anx_score,str_score,dep_time,anx_time,str_time
0,IN,2,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,1,12,1,10,2,1,2,NaN,41,48,54,30.46,40.71,28.83
1,US,2,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,1,2,7,0,70,2,1,4,NaN,38,31,41,28.89,31.65,39.47
2,PL,2,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,1,4,3,60,1,1,3,NaN,53,26,31,21.86,31.28,46.85
3,US,2,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,1,2,4,5,70,2,1,5,biology,30,31,30,25.84,45.09,29.08
4,MY,2,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,2,3,10,1,10,2,1,4,Psychology,46,54,43,35.33,26.46,38.22

### Depression, Anxiety and Stress Categories

Here we will create a column to classify the level of depression, anxiety and stress of the respondent per the [scoring guide](https://neurocogsystem.com/wp-content/uploads/2021/02/DASS-42-Scoring.pdf).

For _depression_, the score classifications are as follows:
   * **Under 10:** Not depressed
   * **10-13:** Mildly depressed
   * **14-20:** Moderately depressed
   * **21-27:** Severely depressed
   * **28+:** Extremely severe depression
    
For _anxiety_ the classifications are:
   * **Under 8:** Not anxious
   * **8-9:** Mildly anxious
   * **10-14:** Moderately anxious
   * **15-19:** Severely anxious
   * **20+:** Extremely severe anxiety
    
Finally, for _stress_ the classifications are:
   * **Under 15**: Not stressed
   * **15-18**: Mildly stressed
   * **19-25**: Moderately stressed
   * **26-33:** Severely stressed
   * **34+:** Extremely severe stress

In [142]:
data['dep_cat']=np.select([data['dep_score'] < 10, 
                           data['dep_score'].between(10,14),
                           data['dep_score'].between(14,21),
                           data['dep_score'].between(21,28),
                           data['dep_score'] >= 28],
                           ['None', 'Mild', 'Moderate', 'Severe', 'Extreme'])

data['anx_cat'] = np.select([data['anx_score'] < 8, 
                             data['anx_score'].between(8,10),
                             data['anx_score'].between(10,15),
                             data['anx_score'].between(15,20),
                             data['anx_score'] >= 20],
                             ['None', 'Mild', 'Moderate', 'Severe', 'Extreme'])

data['str_cat'] = np.select([data['str_score'] < 15, 
                             data['str_score'].between(15,19),
                             data['str_score'].between(19,26),
                             data['str_score'].between(26,34),
                             data['str_score'] >= 34],
                             ['None', 'Mild', 'Moderate', 'Severe', 'Extreme'])

In [143]:
data.head()

,country,source,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,uniquenetworklocation,hand,religion,orientation,race,voted,married,familysize,major,dep_score,anx_score,str_score,dep_time,anx_time,str_time,dep_cat,anx_cat,str_cat
0,IN,2,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,1,12,1,10,2,1,2,NaN,41,48,54,30.46,40.71,28.83,Extreme,Extreme,Extreme
1,US,2,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,1,2,7,0,70,2,1,4,NaN,38,31,41,28.89,31.65,39.47,Extreme,Extreme,Extreme
2,PL,2,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,1,4,3,60,1,1,3,NaN,53,26,31,21.86,31.28,46.85,Extreme,Extreme,Severe
3,US,2,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,1,2,4,5,70,2,1,5,biology,30,31,30,25.84,45.09,29.08,Extreme,Extreme,Severe
4,MY,2,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,2,3,10,1,10,2,1,4,Psychology,46,54,43,35.33,26.46,38.22,Extreme,Extreme,Extreme

### TIPI Classifications

The methodology for the TIPI or Ten-Item Personality Inventory can be found [here](http://gosling.psy.utexas.edu/wp-content/uploads/2014/09/tipi.pdf)

The categories assessed in this test are:
   * Extraversion
   * Agreeableness
   * Conscientiousness
   * Emotional Stability
   * Openness to Experiences

There are two questions per category. One where the item is assessed by the number the respondent put, and one that is it's opposite where the number is inversed. Since these are 7 levels in this survey, the inverse would be the number the survey respondent entered subtracted from 7. The questions for each category are:
   * _Extraversion:_ 1 and 6 reversed
   * _Agreeableness:_ 7 and 2 reversed
   * _Conscientiousness:_ 3 and 8 reversed
   * _Emotional Stability:_ 9 and 4 reversed
   * _Openness to Experiences:_ 5 and 10 reversed

In order to assess the traits of the survey respondent one should take the face value of the first question and average it with the reversed value of the second question. We will create a column for each trait and input the average that we come to for each respondent. After this we will drop the individual TIPI questions in favor of the score per trait.

In [144]:
# a list of the tipi questions that are taken at face value
normal_tipis = ['TIPI' + str(i) for i in range(1,11,2)]

# a list of the tipi questions that are reversed
reverse_tipis = ['TIPI' + str(i) for i in range(1,11) if i % 2 == 0]

In [145]:
# reverse the value for the appropriate tipis
data[reverse_tipis] = 7 - data[reverse_tipis]

In [146]:
# a list of each personality trait
personalities = ['extraversion', 'agreeableness', 'conscientiousness', 'stability', 'openness']

# get the average for the appropriate questions. Each are 5 digits away from eachother
for i in personalities:
    data[i] = (data['TIPI' + str(personalities.index(i) + 1)] + data['TIPI' + str(personalities.index(i) + 6)]) / 2

In [147]:
# drop the tipi questions now that we have the other scores
data = data.drop(columns=normal_tipis + reverse_tipis)

### Word Definition Knowledge

In this section we will make a column indicating whether the responder expressed that they knew the definition of a word that does not exist. This will be 'True' if VCL6, VCL9 or VCL12 is 1, and otherwise False.

After this we will drop the VCL question responses.

In [148]:
# create a column where True if VCL6, 9 or 12 is 1 otherwise False
data['invalid_word'] = np.select([data['VCL6'] == 1, 
                                  data['VCL9'] == 1,
                                  data['VCL12'] == 1],
                                  [True, True, True], False)

In [149]:
# create a list of VCL# columns
words = ['VCL' + str(i) for i in range(1,17)]

### Drop Unnecessary Columns

Here we will remove the columns for the depression, anxiety and stress scores in favor of their categorical column. We will also be dropping uniquenetworklocation since we will be assuming that all responses are from unique individuals. Finally source and screensize will be dropped as they are unlikely to be related to our target of depression score and might thus add noise to the data.

In [150]:
# drop VCL columns in favor of invalid_word column
data = data.drop(columns=words)

### View Datatypes

In [151]:
# drop unneeded columns
data = data.drop(columns = ['dep_score', 'anx_score', 'str_score', 'uniquenetworklocation', 'screensize', 'source'], errors='ignore')

### Convert Datatypes

Here we will convert column datatypes to support pandas NA and make it easy to one-hot encode them with pandas get_dummies

In [153]:
type_dict = {'country': 'category',
             'education': 'category',
             'urban': 'category',
             'engnat': 'category',
             'gender': 'category',
             'hand': 'category',
             'orientation': 'category',
             'race': 'category',
             'voted': 'category',
             'married': 'category',
             'major': 'category',
             'religion': 'category',
             'invalid_word': bool}
data = data.astype(type_dict)
data = data.convert_dtypes()

### Unique Value Count

In [152]:
# get types for each column
get_dtypes(data)

We have 145 unique countries in this dataset, 5309 unique majors and 79 unique ages for the values that did not have drop-down type inputs.

### Unique Categorical Variables

In [155]:
unique_vals(data)

We can see in the above dataframe that there are various misspellings, abbreviations, synonymous entries, and improper entries such as 'Not sure :)'. 'University of Suffolk' and 'Hahahahaha'. With thousands of entries, in this case we will convert all of the entries to lowercase, strip any extra whitespace, remove any special characters, and split the entries to just include the first word if we find ourselves with a sentence. We will also spellcheck what we have left, and ideally have a little mor

In [156]:
# make all majors lowercase
data['major'] = data.major.str.lower()

# strip extra whitespace from majors
data['major'] = data.major.str.strip()

# replace any special characters with a space
data['major'] = data.major.str.replace('\W', ' ', regex=True)

# replace whitespace of more than 1 character with just one whitespace
data['major'] = data.major.str.replace('  +', ' ', regex=True)

# split the values into a list
data['major'] = data.major.str.split()

# make major the first value from the list
data['major'] = data.major.str[0]

In [157]:
# import and initialize spellchecker
from spellchecker import SpellChecker
spell = SpellChecker(distance=1)

# function check the spelling of leftover words
def Correct(x):
    return spell.correction(str(x))

# apply the function to the series
data['major'] = data['major'].apply(Correct)

In [158]:
# replace the now-string nan with actual NA values
data['major'] = data.major.replace({'nan':None, 'None':None})

In [159]:
# get number of unique majors
data.major.nunique()

1039

We have gone from over 5000 to just over 1000 different majors with these transformations, which makes it more likely reveal something interesting when we assess the relationship of depression to majors if there is one. Here are the top 10 most common, non-NaN majors.

In [160]:
# dataframe of 10 most common major values
pd.DataFrame(data.major.value_counts()[0:10])

             major
psychology    1920
english       1571
business      1433
engineering   1155
accounting    1015
computer       888
law            712
science        682
civil          626
medicine       525

### Null Values

There are no Duplicate Values

We have 11,447 null values for major, which likely indicate people who are not in college or otherwise may be pursuing general studies.

There are two null values for country which can be viewed below:

In [162]:
# dataframe subset of countries missing values
data[data.country.isna()]

,country,education,urban,gender,engnat,age,hand,religion,orientation,race,voted,married,familysize,major,dep_time,anx_time,str_time,dep_cat,anx_cat,str_cat,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word
3526,NaN,3,3,2,1,42,1,3,3,60,2,3,2,industrial,54.4,23.05,22.55,Moderate,Extreme,Severe,3.0,3.5,6.0,2.5,5.0,False
23744,NaN,2,2,1,1,20,1,1,2,60,2,1,3,None,29.94,32.85,37.22,Extreme,Extreme,Extreme,3.0,1.0,4.0,1.0,5.0,False

For both of these we will enter the most common country in our data to remove the nulls.

In [163]:
# changing the null country values with most common country
data[data.country.isna()]['country'] = data.country.value_counts().index[0]

### Statistical Information

In [161]:
# dataframe of each column and their count of nulls
null_vals(data)

Above we can see that the maximum age is 1,998. Likely this is someone entering their birthyear. We can see all who listed their age as over 100 in the dataframe below.

In [165]:
data.loc[data['age'] > 100]

,country,education,urban,gender,engnat,age,hand,religion,orientation,race,voted,married,familysize,major,dep_time,anx_time,str_time,dep_cat,anx_cat,str_cat,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word
5340,MY,3,1,2,2,223,1,10,1,10,2,1,5,law,20.09,57.42,22.49,Moderate,Extreme,Moderate,6.0,2.5,5.5,5.0,5.5,False
10231,MY,2,3,2,2,1996,1,10,5,10,2,1,4,teaching,25.18,36.72,38.1,Extreme,Extreme,Extreme,2.5,3.5,5.5,2.5,2.5,False
14236,US,2,3,2,1,117,1,7,3,60,2,1,2,None,32.84,31.52,35.64,Extreme,Extreme,Extreme,2.0,4.0,1.0,1.0,2.5,False
21383,MY,3,3,2,2,1998,1,10,4,10,2,1,3,banking,39.62,25.67,34.7,Moderate,Severe,Moderate,0.0,3.5,3.5,0.5,3.5,False
24898,AR,1,3,2,2,115,1,4,3,70,2,1,2,None,31.49,32.28,36.23,Extreme,Severe,Moderate,3.0,4.0,2.0,1.5,3.0,False
30027,MY,3,1,2,2,1993,1,10,1,10,2,2,6,quantity,23.11,43.91,32.98,Extreme,Extreme,Extreme,2.0,4.0,4.0,1.0,3.5,False
33730,MY,3,2,1,2,1991,1,2,1,10,2,1,3,interior,29.56,36.51,33.93,Extreme,Extreme,Extreme,2.0,3.5,4.0,1.0,2.5,False

Some respondents entered their birthyear, others seem to have just put unlitely numbers. For these, since there are only seven entries with an age over 100, we will change these ages to the median age for all respondents to remove these unlikely outliers.

In [164]:
# dataframe of statistical description of variables
data.describe()

,age,familysize,dep_time,anx_time,str_time,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word
count,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775.000000,39775
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34583
mean,23.612168,3.510270,30.149799,35.060519,34.789705,2.967278,4.040377,3.730660,2.738290,4.101634,NaN
std,21.581722,2.141518,9.022322,9.274750,9.507810,1.555143,1.229776,1.491769,1.527743,1.335035,NaN
min,13.000000,0.000000,0.020000,0.080000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,18.000000,2.000000,25.640000,30.530000,29.985000,1.500000,3.500000,2.500000,1.500000,3.500000,NaN
50%,21.000000,3.000000,29.580000,34.770000,33.920000,3.000000,4.000000,3.500000,2.500000,4.000000,NaN
75%,25.000000,4.000000,33.830000,39.045000,38.450000,4.000000,5.000000,5.000000,3.500000,5.000000,NaN
max,1998.000000,133.000000,99.840000,99.950000,99.710000,7.000000,7.000000,7.000000,7.000000,7.000000,NaN

We can also see in the above description that the maximum family size is 133. Let's take a look at the top family sizes in the dataframe below of all families with a family size of over 20.

In [167]:
data.loc[data['familysize'] > 20]

,country,education,urban,gender,engnat,age,hand,religion,orientation,race,voted,married,familysize,major,dep_time,anx_time,str_time,dep_cat,anx_cat,str_cat,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word
1174,US,1,1,2,1,14,1,2,3,70,2,1,62,None,35.51,28.0,36.49,Extreme,Extreme,Extreme,0.5,3.0,3.5,2.5,2.5,True
16897,GB,3,3,1,2,22,1,10,5,10,1,3,99,business,58.41,20.15,21.45,Extreme,Extreme,Extreme,3.5,3.5,3.5,3.5,3.5,False
18268,AU,2,3,2,2,16,1,10,5,10,2,1,54,None,27.13,32.28,40.6,Extreme,Extreme,Extreme,4.0,3.0,3.5,2.0,5.0,False
19781,MY,4,2,1,1,60,3,10,5,40,1,2,65,malay,14.84,50.86,34.3,Mild,Severe,Mild,3.5,2.5,3.5,3.5,3.5,True
20779,MY,4,1,2,1,29,3,10,2,10,1,3,26,psychology,23.3,27.26,49.44,Extreme,Extreme,Extreme,3.5,3.5,3.5,3.5,3.5,True
29800,NZ,1,1,3,2,19,3,10,2,10,2,1,24,photography,1.27,97.32,1.4,Extreme,Extreme,Extreme,0.5,6.5,2.0,4.5,5.5,True
34247,MY,2,3,1,2,21,1,10,1,10,2,1,21,networking,44.73,22.74,32.52,Extreme,Extreme,Extreme,1.5,3.0,1.5,3.5,2.5,False
34829,NONE,3,2,2,1,19,1,6,1,10,1,1,23,english,54.14,25.33,20.53,Extreme,Extreme,Severe,2.0,4.0,3.5,4.0,4.0,True
34901,US,1,1,3,1,99,3,12,4,20,2,1,133,none,31.92,38.25,29.83,Extreme,Extreme,Extreme,0.5,0.5,0.5,0.5,2.0,False

Since there are so few in our dataset, and it is unlikely to have a family size of say, 99, we will exchange these numbers with the median family size to remove these outliers.

In [168]:
data.country.value_counts(normalize=True).drop('NONE')[0:10].index

CategoricalIndex(['MY', 'US', 'GB', 'CA', 'ID', 'PH', 'AU', 'IN', 'DE', 'SG'], categories=['AE', 'AF', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', ...], ordered=False, dtype='category')

In [166]:
data.loc[data['age'] > 100, 'age'] = data.age.median()

Another problem comes up in the dataframe above, where one person has a country 'NONE'.

In [170]:
# find all rows where country == NONE
data.loc[data.country == 'NONE']

,country,education,urban,gender,engnat,age,hand,religion,orientation,race,voted,married,familysize,major,dep_time,anx_time,str_time,dep_cat,anx_cat,str_cat,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word
39,NONE,2,3,1,2,26,2,7,1,60,1,1,3,None,33.02,35.33,31.65,Moderate,Moderate,Moderate,4.0,2.0,4.0,5.0,6.0,False
214,NONE,4,1,1,1,41,1,4,1,60,2,1,4,science,22.79,37.71,39.5,Extreme,Extreme,Severe,3.5,3.5,4.5,2.5,4.5,False
228,NONE,3,2,2,2,30,3,7,1,60,1,2,3,mechanical,34.04,30.76,35.19,Severe,Severe,Severe,2.5,2.0,4.5,3.0,3.0,False
324,NONE,2,2,1,1,68,1,12,1,60,1,3,5,fine,28.76,33.27,37.97,Mild,Severe,Mild,3.5,5.0,5.5,6.0,5.5,False
419,NONE,2,1,2,1,21,1,1,1,70,1,1,3,information,31.78,37.87,30.35,Extreme,Extreme,Extreme,0.5,2.0,3.5,2.5,4.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39499,NONE,3,3,2,2,21,1,10,1,10,2,1,3,biotechnology,24.85,31.81,43.34,Extreme,Extreme,Extreme,3.0,5.0,6.0,1.0,2.0,False
39556,NONE,3,3,2,2,25,1,4,1,70,1,1,2,human,30.23,40.52,29.25,Mild,Extreme,Moderate,3.5,5.5,4.5,3.5,4.5,False
39611,NONE,1,3,1,2,19,1,2,4,60,0,1,2,None,24.08,36.98,38.94,Extreme,Severe,Moderate,2.0,2.0,3.0,3.5,3.0,False
39617,NONE,3,3,1,1,40,1,6,3,30,1,1,3,double,35.39,34.59,30.01,Moderate,Severe,Mild,5.0,5.5,2.5,3.5,5.5,False
39719,NONE,2,3,0,1,28,0,0,1,60,2,1,2,None,49.66,33.94,16.4,Extreme,Extreme,Extreme,3.5,3.5,3.5,1.0,5.0,False

We have 539 rows where the respondent's country did not register. 

We will impute these datapoints with the top 10 most common countries following a similar distribution to what these countries are already at.

In [172]:
# assign random value to country nearly matching the current distribution of countries.
data.loc[data.country == 'NONE', 'country'] = np.random.choice(data.country.value_counts(normalize=True).drop('NONE').index[0:10], 
                                                          p=[0.55, 0.21, 0.04, 0.04, 0.04, .03, .03, .02, .02, .02])

In [33]:
data = data[['country', 'education', 'urban', 'engnat', 'age', 'gender', 'orientation',
             'race', 'married', 'familysize', 'voted', 'hand', 'major', 'religion',
             'dep_time', 'anx_time', 'str_time', 'anx_cat', 'str_cat',
             'extraversion', 'agreeableness', 'conscientiousness', 'stability',
             'openness', 'invalid_word', 'dep_cat']]

In [34]:
data.head()

,country,education,urban,engnat,age,gender,orientation,race,married,familysize,voted,hand,major,religion,dep_time,anx_time,str_time,anx_cat,str_cat,extraversion,agreeableness,conscientiousness,stability,openness,invalid_word,dep_cat
0,IN,2,3,2,16,2,1,10,1,2,2,1,nan,12,30.46,40.71,28.83,Extreme,Extreme,0.5,4.5,4.5,0.5,6.5,False,Extreme
1,US,2,3,1,16,2,0,70,1,4,2,2,nan,7,28.89,31.65,39.47,Extreme,Extreme,4.5,4.5,2.0,0.5,3.5,False,Extreme
2,PL,2,3,2,17,2,3,60,1,3,1,1,nan,4,21.86,31.28,46.85,Extreme,Severe,1.5,3.5,2.0,4.0,5.0,False,Extreme
3,US,1,3,1,13,2,5,70,1,5,2,2,biology,4,25.84,45.09,29.08,Extreme,Severe,2.0,6.0,6.5,4.5,6.0,False,Extreme
4,MY,3,2,2,19,2,1,10,1,4,2,3,psychology,10,35.33,26.46,38.22,Extreme,Extreme,2.0,3.5,2.0,2.0,4.5,False,Extreme

In [36]:
data.dtypes

country              category
education              object
urban                  object
engnat                 object
age                     Int64
gender                 object
orientation            object
race                   object
married                object
familysize              Int64
voted                  object
hand                   object
major                  object
religion               object
dep_time              Float64
anx_time              Float64
str_time              Float64
anx_cat                string
str_cat                string
extraversion          Float64
agreeableness         Float64
conscientiousness     Float64
stability             Float64
openness              Float64
invalid_word          boolean
dep_cat                string
dtype: object

In [37]:
pd.DataFrame(data.corr().sort_values(by='dep_cat')['dep_cat'])

KeyError: 'dep_cat'

In [ ]:
from sklearn.model_selection import train_test_split

# split stud_info clicks into train/test sets stratified by module_presentation
train, test = train_test_split(data, test_size=0.2, random_state=42)

### Country

In [ ]:
# set the color palette for graph
sns.set_palette('pastel')
import matplotlib.ticker as mtick

# make a bar graph with a normalized y axis of percent of students per country
plt.figure(figsize=(30, 15))
plt.title('Survery Participant Country Distribution')
ax = sns.countplot(y=train.country, order=train.country.value_counts(normalize=True).iloc[:10].index)
ax.xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1, decimals=None, symbol='%', is_latex=False))
plt.show()

In [ ]:
# set the color palette for graph
sns.set_palette('pastel')

# make a bar graph with a normalized y axis of percent of students per country
plt.figure(figsize=(30, 15))
plt.title('Survery Participant Country Distribution')
ax = sns.countplot(y=train.country, order=train.country.value_counts().iloc[:10].index, hue=train.dep_cat)
#ax = (pd.Series(train['country']).value_counts(normalize=True, ascending=False)*100).plot.bar(order=train.country.value_counts().iloc[:10].index).set(ylabel='Percent of Students')
plt.show()

In [ ]:
pd.DataFrame(data.country.value_counts(normalize=True))[0:10]

### Education

In [ ]:
# list of education possibilities in order 
educations = ['Below High School', 'High School', 'University Degree', 'Graduate Degree', 'No Response']

# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('Respondent Education Distribution')
sns.countplot(data=train, x=train['education'], order=educations).set(xlabel= 'Respondent Education Level', ylabel='Respondent Count')
plt.show()

In [ ]:
# list of education possibilities in order 
educations = ['Below High School', 'High School', 'University Degree', 'Graduate Degree', 'No Response']

# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('Respondent Education Distribution')
sns.countplot(data=train, x=train['education'], order=educations, hue=train.dep_cat).set(xlabel= 'Respondent Education Level', ylabel='Respondent Count')
plt.show()

### Urban

In [ ]:
# list of education possibilities in order 
urbans = ['Urban', 'Suburban', 'Rural', 'No Response']

# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('Respondent Childhood Locations')
sns.countplot(data=train, x=train['urban'], order=urbans).set(xlabel='Respondent Childhood Location Type', ylabel='Respondent Count')
plt.show()

In [ ]:
# list of education possibilities in order 
urbans = ['Urban', 'Suburban', 'Rural', 'No Response']

# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('Respondent Childhood Locations')
sns.countplot(data=train, x=train['urban'], order=urbans, hue=train.dep_cat).set(xlabel='Respondent Childhood Location Type', ylabel='Respondent Count')
plt.show()

### English National

In [ ]:
engnats = ['Yes', 'No', 'No Response']
# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('English as National Language')
sns.countplot(data=train, x=train['engnat'], order=engnats).set(xlabel='Whether English is Respondents National Language', ylabel='Respondent Count')
plt.show()

In [ ]:
engnats = ['Yes', 'No', 'No Response']
# create a bar graph/count plot of students per education level
plt.figure(figsize=(20, 3))
plt.title('English as National Language')
sns.countplot(data=train, x=train['engnat'], order=engnats).set(xlabel='Whether English is Respondents National Language', ylabel='Respondent Count')
plt.show()

### Age

In [ ]:
plt.figure(figsize=(20, 10))
sns.countplot(train.age)
plt.show()

### Gender

In [ ]:
genders = ['M', 'F', 'O', 'No Response']
sns.countplot(train.gender, order=genders)
plt.show()

### Orientation

In [ ]:
sns.countplot(train.orientation, order=train.orientation.value_counts().iloc[:].index)
plt.show()

### Race

In [ ]:
plt.figure(figsize=(15, 5))
sns.countplot(train.race, order=train.race.value_counts().iloc[:].index)
plt.show()

### Religion

In [ ]:
plt.figure(figsize=(23, 5))
sns.countplot(train.religion, order=train.religion.value_counts().iloc[:].index)
plt.show()

### Marital Status

In [ ]:
plt.figure(figsize=(15, 5))
sns.countplot(train.married, order=train.married.value_counts().iloc[:].index)
plt.show()

### Family Size

In [ ]:
sns.countplot(train.familysize)
plt.show()

### Voted

In [ ]:
sns.countplot(train.voted, order=train.voted.value_counts().iloc[:].index)
plt.show()

### Hand

In [ ]:
sns.countplot(train.hand, order=train.hand.value_counts().iloc[:].index)
plt.show()

### Major

In [ ]:
# make a bar graph with a normalized y axis of percent of students per country
plt.figure(figsize=(30, 15))
plt.title('Survery Participant Country Distribution')
ax = sns.countplot(y=train.major, order=train.major.value_counts().iloc[:10].index)
plt.show()

### Time spent on Depression Questions

In [ ]:
sns.displot(train, x='dep_time')
plt.show()

### Time Spent on Anxiety Questions

In [ ]:
sns.displot(train, x='anx_time')
plt.show()

### Time Spent on Stress Questions

In [ ]:
sns.displot(train, x='str_time')
plt.show()

### Extraversion

In [ ]:
sns.countplot(train.extraversion)
plt.show()

### Agreeableness

In [ ]:
sns.countplot(train.agreeableness)
plt.show()

### Conscientiousness

In [ ]:
sns.countplot(train.conscientiousness)
plt.show()

### Emotional Stability

In [ ]:
sns.countplot(train.stability)
plt.show()

### Openness

In [ ]:
sns.countplot(train.openness)
plt.show()

### Claim to know a word that doesn't exist

In [ ]:
sns.countplot(train.invalid_word)
plt.show()

### Anxiety Level

In [ ]:
sns.countplot(train.anx_cat)
plt.show()

### Stress Level

In [ ]:
sns.countplot(train.str_cat)
plt.show()

### Depression Level

In [ ]:
sns.countplot(train.dep_cat)
plt.show()

In [ ]:
dummy = pd.get_dummies(data)

In [ ]:
get_kbest(dummy)

http://gosling.psy.utexas.edu/wp-content/uploads/2014/09/tipi.pdf

In [ ]:
http://gosling.psy.utexas.edu/wp-content/uploads/2014/09/tipi.pdf